### ISSUE TITLE
放大镜在边缘会触发显示滚动条

### ISSUE THREAD

**Issue by ryanfwy** [ryanfwy/jike-calendar#3]
放大镜在边缘会触发显示滚动条，实际没啥意义，只是移过去会显示完整的放大镜。
![image](https://user-images.githubusercontent.com/14328312/53141793-7a1f8f80-35cc-11e9-916f-3744c5b8982c.png)

_Originally posted by @ParfoisMeng in https://github.com/ryanfwy/jike-calendar/issues/1#issuecomment-465848852_

**Comment by ryanfwy** [comment]
@ParfoisMeng 修复了，关乎下一版更新哈。Thanks :)

**Comment by ParfoisMeng** [comment]
@ryanfwy 效率点赞！👍

**Comment by ryanfwy** [comment]
修复见 [Version 0.5.0](https://github.com/ryanfwy/jike-calendar/releases/tag/v0.5.0)。
