### ISSUE TITLE
交流

### ISSUE THREAD

**Issue by Dawninest** [ryanfwy/jike-calendar#4]
从即刻慕名而来,
因为我也想整一个dock栏 黄历, 不过我是 macOS 原生开发啦,
之前在纠结如何从即刻App中抓到探索页中日历的数据(就是今日宜怎么怎么样那个),
不过看了你的代码,貌似你的的数据也不是拿的那个数据,
不过也真亏你能想到去拿某几个专栏的数据[计划通],佩服佩服,

我即刻与GitHub同ID,不如,咱即刻见?

**Comment by ryanfwy** [comment]
哈哈哈，说慕名而来就客气了。多交流多交流🌚
